name: ashok_leyland_project_3
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  getflutter: ^1.1.3
  google_fonts: ^2.0.0
  material_floating_search_bar: ^0.3.5
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
