name: ashok_leyland_project_3
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^9.2.0
  getflutter: ^1.1.3
  google_fonts: ^2.0.0
  hexcolor: ^2.0.5
  intl: ^0.17.0
  material_floating_search_bar: ^0.3.5
  provider: ^6.0.1
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
